# Generated by Django 6.0 on 2025-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('challenge', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('techStack', models.JSONField(default=list)),
                ('liveLink', models.URLField()),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
