# Generated by Django 6.0 on 2025-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('shortDescription', models.TextField()),
                ('description', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('process', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
