# Generated by Django 6.0 on 2025-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('publishedDate', models.DateField(auto_now_add=True)),
                ('readTime', models.CharField(max_length=50)),
            ],
        ),
    ]
