# Generated by Django 6.0.3 on 2026-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='deployment_date',
            field=models.DateTimeField(blank=True, help_text='Actual project deployment date', null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
    ]
