# Generated by Django 5.2.10 on 2026-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_consent_deployment_date_consent_version_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='final_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='is_final_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
