# Generated by Django 6.0.3 on 2026-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_consent_final_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='maintenance_duration_months',
            field=models.IntegerField(default=12, help_text='Maintenance duration in months'),
        ),
    ]
