# Generated by Django 6.0 on 2025-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(default='Webora Solutions', max_length=255)),
                ('tagline', models.CharField(default='Building Your Digital Presence', max_length=255)),
                ('email', models.EmailField(default='info@weborasolutions.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('address', models.TextField(default='123 Tech Street, San Francisco, CA 94102')),
                ('social', models.JSONField(default=dict)),
                ('hero', models.JSONField(default=dict)),
                ('about', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
