# Generated by Django 5.2.10 on 2026-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='companyName',
            field=models.CharField(default='DigitalCore Solutions', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='info@digitalcoresolutions.com', max_length=254),
        ),
    ]
