# Generated by Django 5.2.10 on 2026-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesetting_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='companyName',
            field=models.CharField(default='Digital Core', max_length=255),
        ),
    ]
